---
- hosts: rhel
  name: This is a RHEL list patching playbook (*,security, available, installed,updates, repos)
  tasks: 
    - name:  all packages
      yum:
        list: '{{ packagename }}' 
      notify: Reboot host
      register: yumcommandout

    - name: Print errors if yum failed
      debug:
        msg: "yum command produced errors"
      when: yumcommandout is not defined

    - name: display yum list result
      debug:
        var: yumcommandout

  handlers:
    - name: Reboot host
      reboot:
        msg: "Rebooting after update"
        connect_timeout: 5
        reboot_timeout: 600
        test_command: id
