---
- hosts: rhel
  name: This is a RHEL patching playbook
  tasks: 
    - name: Update all packages
      yum:
        name: '{{ packagename }}'
        state: latest
      notify: Reboot host
      
  handlers:
    - name: Reboot host
      reboot:
        msg: "Rebooting after update"
        connect_timeout: 5
        reboot_timeout: 600
        test_command: id
      when: 'yes' == '{{ reboot_server }}'
