---
- hosts: 192.168.1.99
  name: actualiza stored procedures en oracle
 
  tasks: 
    - name: ejecuta comando
      shell: sudo su - oracle -c "echo exit| echo @sample.pl | sqlplus / as sysdba"
      args:
        chdir: /home/oracle
        executable: /bin/bash
        
    - name: Print output
      debug:
        msg: "termino actualizacion"
