---
- hosts: 192.168.1.99
  name: actualiza stored procedures en oracle
  become: yes
  become_user: oracle
  tasks: 
    - name: ejecuta comando
      shell: echo exit| echo @sample.pl | sqlplus / as sysdba
      args:
        chdir: /home/oracle
        executable: /bin/bash
        
    - name: Print output
      debug:
        msg: "termino actualizacion"
