---
- hosts: 192.168.1.99
  name: actualiza stored procedures en oracle
  become: yes
 
  tasks: 
    - name: copia archivo fuente
      copy:
        src: sample.pl
        dest: /home/oracle/carga.pl
        owner: oracle
        group: oinstall
        mode: u=rw,g=r,o=r
  
    - name: ejecuta comando
      shell: su - oracle -c "echo exit| echo @carga.pl | sqlplus / as sysdba"
      args:
        chdir: /home/oracle
        executable: /bin/bash
        
    - name: Print output
      debug:
        msg: "termino actualizacion"
